/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JapaRouteImport } from './routes/japa'
import { Route as MurtiRouteImport } from './routes/murti'
import { Route as PathRouteImport } from './routes/path'
import { Route as PujaRouteImport } from './routes/puja'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JapaRoute = JapaRouteImport.update({
  id: '/japa',
  path: '/japa',
  getParentRoute: () => rootRouteImport,
} as any)
const MurtiRoute = MurtiRouteImport.update({
  id: '/murti',
  path: '/murti',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const PujaRoute = PujaRouteImport.update({
  id: '/puja',
  path: '/puja',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/japa': typeof JapaRoute
  '/murti': typeof MurtiRoute
  '/path': typeof PathRoute
  '/puja': typeof PujaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/japa': typeof JapaRoute
  '/murti': typeof MurtiRoute
  '/path': typeof PathRoute
  '/puja': typeof PujaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/japa': typeof JapaRoute
  '/murti': typeof MurtiRoute
  '/path': typeof PathRoute
  '/puja': typeof PujaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/japa' | '/murti' | '/path' | '/puja'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/japa' | '/murti' | '/path' | '/puja'
  id: '__root__' | '/' | '/japa' | '/murti' | '/path' | '/puja'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JapaRoute: typeof JapaRoute
  MurtiRoute: typeof MurtiRoute
  PathRoute: typeof PathRoute
  PujaRoute: typeof PujaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/japa': {
      id: '/japa'
      path: '/japa'
      fullPath: '/japa'
      preLoaderRoute: typeof JapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/murti': {
      id: '/murti'
      path: '/murti'
      fullPath: '/murti'
      preLoaderRoute: typeof MurtiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puja': {
      id: '/puja'
      path: '/puja'
      fullPath: '/puja'
      preLoaderRoute: typeof PujaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JapaRoute: JapaRoute,
  MurtiRoute: MurtiRoute,
  PathRoute: PathRoute,
  PujaRoute: PujaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
